version: 0.2

env:
  variables:
    REPO_URI: 961776040935.dkr.ecr.us-east-1.amazonaws.com/image_repo/aws-fullstack-cicd-react-lambda

phases:
  pre_build:
    commands:
      - echo "Login to ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 961776040935.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - docker build -t image_repo/aws-fullstack-cicd-react-lambda .
      - docker tag image_repo/aws-fullstack-cicd-react-lambda:latest $REPO_URI:latest

  post_build:
    commands:
      - echo "Pushing image"
      - docker push $REPO_URI:latest

      - echo "Preparing EC2 Key..."
      - echo "$EC2_KEY" | sed 's/-----BEGIN\(.*\)PRIVATE KEY----- /\n-----BEGIN\1PRIVATE KEY-----\n/; s/ -----END\(.*\)PRIVATE KEY-----/\n-----END\1PRIVATE KEY-----\n/' | tr -d '\r' > key.pem
      - chmod 400 key.pem

      - echo "Deploying to EC2..."
      - ssh -i key.pem -o StrictHostKeyChecking=no -o PubkeyAcceptedAlgorithms=+ssh-rsa ec2-user@54.204.239.16 "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 961776040935.dkr.ecr.us-east-1.amazonaws.com && docker pull 961776040935.dkr.ecr.us-east-1.amazonaws.com/image_repo/aws-fullstack-cicd-react-lambda:latest && sudo docker stop app || true && sudo docker rm app || true && sudo docker run -d -p 80:80 --name app 961776040935.dkr.ecr.us-east-1.amazonaws.com/image_repo/aws-fullstack-cicd-react-lambda:latest"