version: 0.2

env:
  variables:
    REPO_URI: 961776040935.dkr.ecr.us-east-1.amazonaws.com/image_repo/aws-cicd-event-driven-platform
    ECR_DOMAIN: 961776040935.dkr.ecr.us-east-1.amazonaws.com
    INSTANCE_ID: i-08f00525b20b26287

phases:
  pre_build:
    commands:
      - echo "Authenticating with ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_DOMAIN

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPO_URI:latest .

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $REPO_URI:latest

      - echo "Executing remote deployment via AWS SSM..."
      - aws ssm send-command --instance-ids "$INSTANCE_ID" --document-name "AWS-RunShellScript" --parameters "commands=['aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin $ECR_DOMAIN', 'sudo docker pull $REPO_URI:latest', 'sudo docker stop app || true', 'sudo docker rm app || true', 'sudo docker run -d -p 80:80 --name app $REPO_URI:latest']" --region us-east-1