import './App.css'

function App() {
  return (
    <div className="container">
      <h1>Deployment Lab</h1>
      
      <div className="focus-box">
        <h2>CI/CD Focus</h2>
        <p>
          This project is primarily designed to explore and demonstrate 
          <strong> CI/CD workflows and AWS services integration </strong> 
          using Docker, Amazon ECR, CodeBuild, and CodePipeline.
        </p>
        <p>
          The React code itself is a functional baseline generated by 
          <strong> Google Antigravity</strong> to serve as the payload for the deployment pipeline.
        </p>
      </div>

      <div className="version-note">
        This is version 4, this will change to test the CICD
      </div>
    </div>
  )
}

export default App
