import { useState } from 'react'
import './App.css'

function App() {
  const [data, setData] = useState<any[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleTrigger = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch('https://w4c81vr7k6.execute-api.us-east-1.amazonaws.com/user/getUserCatchphrase');
      if (!response.ok) throw new Error('Failed to fetch data');
      const result = await response.json();
      setData(result);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container">
      <h1>Deployment Lab</h1>
      
      <div className="focus-box">
        <h2>CI/CD Focus</h2>
        <p>
          This project is primarily designed to explore and demonstrate 
          <strong> CI/CD workflows and AWS services integration </strong> 
          using Docker, Amazon ECR, CodeBuild, and CodePipeline.
        </p>
        <p>
          The React code itself is a functional baseline generated by 
          <strong> Google Antigravity</strong> to serve as the payload for the deployment pipeline.
        </p>
      </div>

      <div className="focus-box">
        <h2>Additional Project: aws-fullstack-cicd-react-lambda</h2>
        <p>
          Full-stack AWS project using React (Docker on EC2) integrated with a serverless backend 
          (API Gateway + Lambda), deployed via a CI/CD pipeline using CodePipeline, CodeBuild, and ECR.
        </p>
        <button 
          className="trigger-button" 
          onClick={handleTrigger}
          disabled={loading}
        >
          {loading ? 'Triggering...' : 'Trigger'}
        </button>

        {error && <div className="error-message">Error: {error}</div>}

        {data && (
          <div className="api-results">
            {data.map((user: any) => (
              <div key={user.id} className="result-item">
                <span className="user-name">{user.name}:</span>
                <span className="user-phrase">"{user.catchphrase}"</span>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="version-note">
        This is version 8, this will change to test the CICD
      </div>
    </div>
  )
}

export default App
